server:
  port: 80
spring:
  thymeleaf:
    mode: HTML

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8
    username: root
    password: root

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hhtt.blog.pojo




